### ISSUE TITLE
tps and one suggestion

### ISSUE THREAD

**Issue by DoomSquirter** [Beyond-Reality/Beyond-Realty-Farscapes#1]
After playing for about 10 minutes, tps was 6 and when I save/quit it just hung at closing mc screen.  something's getting stuck but no clue what.  logs aren't real helpful.

one suggestion:
Actually additions config:
    # The chances for lush caves to generate. The lower the number, the higher the chances.
    I:"Lush Caves: Chance"=20

I'd suggest 0?  or 1 if you still want them to appear.  Nobody I know likes these things and they are more nuisance than anything.  These are the underground 'forests" that generate like everywhere.

**Comment by Dominance** [comment]
I'm working on wood generation and Will have changed ether later tonight or first thing tomorrow. How ever the 6fps has to be other issues going on with your PC. Did you try your suggestions out and if so did it impact you're performance?

**Comment by DoomSquirter** [comment]
TPS.  fps was good, 60+ ..  /forge tps showed 6 (note that forge tps doesn't show 20 when good tps is seen anyways, but 6 is much less than 16 or whatever the # it usually shows.  )

note: I wasn't really world genning.  I found 3-4 villages around spawn and was checking them out this entire time.  I know you guys ran this on server but maybe this is a ssp issue?  I told parcipal I wasn't really looking at console or anything at the time.  I will give it another go, even a new world just to see if anything sticks out.
