### ISSUE TITLE
Possible to add Nature's Compass?

### ISSUE THREAD

**Issue by cgalliva** [Beyond-Reality/Beyond-Realty-Farscapes#11]
I don't want to be that guy who spams "ADD ALL MODS" but I think that this would be very a helpful addition. Because we have BOP and there's a lot of possible biomes to look for (I'll admit I'd like this for a specific cliff biome) I think this would be a great help. We also have biome dependent oregen and its not exactly server friendly to randomly wander generating new chunks. 

I know BOP adds a "Biome Finder" but one of the components doesn't appear to be craftable. The core requires 8 gems and the recipe isn't oredict, coupling that with the auto-oredict mod we have I think if I ever found all 8 gems it'd fail to work..

**TL,DR: Add dis plz:**

https://minecraft.curseforge.com/projects/natures-compass

**Comment by Dominance** [comment]
While technically its not biome dependent oregen as everything can generate everywhere, It does have major increased chances in select biomes. Anyhow yeah I think its a great addition myself. Will look into adding in next version increase.
