### ISSUE TITLE
new update quark issues  - can't link in chat and can't edit signs

### ISSUE THREAD

**Issue by DoomSquirter** [Beyond-Reality/Beyond-Realty-Farscapes#15]
newest update on server

can't link items in chat and can't edit signs

**Comment by leagris** [comment]
Disabled to limit quark hooking into mc classes and bugging lots of stuffs

**Comment by leagris** [comment]
- Item linking is `SHIFT` + `T` while hovering an item.
- Sign edit re-enabled in c76792adc49c013c3f5f4d3603d4ed5fe51eb726
