### ISSUE TITLE
Botania sashes jump boost not working

### ISSUE THREAD

**Issue by Crumbology** [Beyond-Reality/Beyond-Realty-Farscapes#17]
https://github.com/Vazkii/Botania/issues/2284#issuecomment-308113842

Tested with just Botania installed, works as intended, no jump boost whatsoever in Farscapes when using sashes.

**Comment by MisterShawn** [comment]
Just to make sure, do you have a mana tablet with some mana in it?

**Comment by Crumbology** [comment]
yep, have plenty of mana in inventory, mirror and a mana ring
