### ISSUE TITLE
Block of gold in RS solderer produces basic circuits not advanced (blockMetal oredict issue)

### ISSUE THREAD

**Issue by katecw** [Beyond-Reality/Beyond-Realty-Farscapes#18]
#### Issue description:

If you put a block of gold in a Refined Storage solderer it produces nine Printed Basic Processors instead of 9 Printed Improved Processors. One gold ingot works as expected (a single improved processor).

Tested twice in two different solderers. JEI shows the correct recipie recipe.

#### Suggested resolution:

I posted this as a RS issue (https://github.com/raoulvdberge/refinedstorage/issues/1301) and they suggested an oredict problem. 

Block of gold has oredicts blockGold & blockMetal. Block of iron has blockIron & blockMetal.

I suggest that the blockMetal oredict tag should be removed from those items. Buuz checked and could find no other items with that tag.

#### Versions:

- Minecraft: 1.11.2
- Forge: 13.20.0.2315
- Refined Storage: 1.4.12

**Comment by leagris** [comment]
I will probably tweak it with:
```Javascript
import minetweaker.item.IItemStack;

// Clear blockMetal oredict entries.

var item = null as IItemStack;
for item in <ore:blockMetal>.items {
  <ore:blockMetal>.remove(item);
}
```

**Comment by raoulvdberge** [comment]
I rewrote the oredict system for solderers in 1.4.13 a bit, if you update you could remove that tweak.
