### ISSUE TITLE
request for recipe involving dragon breath, stars, what not to make a dragon egg

### ISSUE THREAD

**Issue by DoomSquirter** [Beyond-Reality/Beyond-Realty-Farscapes#19]
Only one per world, thus not very SMP friendly.

**Comment by leagris** [comment]
This is 1.11.2: https://minecraft.gamepedia.com/End_Crystal
Craft an end_crystal and use that to spawn a new ender dragon

**Comment by DoomSquirter** [comment]
not the same issue lea.  yes, I used end crystal to spawn dragon.  but it doesn't leave a egg.  it leaves an elytra now after the first dragon death.

**Comment by DoomSquirter** [comment]
http://minecraft.gamepedia.com/Dragon_Egg

**Comment by leagris** [comment]
Have fixed with elytra conversion recipe
