### ISSUE TITLE
latest(only) dev build - crash while generating world

### ISSUE THREAD

**Issue by DoomSquirter** [Beyond-Reality/Beyond-Realty-Farscapes#2]
note: this is not the public farscapes install, this is the dev one.

https://pastebin.com/VySeijh9

**Comment by DoomSquirter** [comment]
note: new install, recommended, removed optifine/betterfonts and same crash genning world.

**Comment by Dominance** [comment]
Yeah its a known issue internally. Remove blank planet and your good. It should of been removed already.

**Comment by MJRLegends** [comment]
You could of said there was a bug haha, i will fix it @Dominance
