### ISSUE TITLE
rod of the seas uncraftable

### ISSUE THREAD

**Issue by DoomSquirter** [Beyond-Reality/Beyond-Realty-Farscapes#21]
potion in top right is "uncraftable potion"

possibly due to potion mod being removed?

**Comment by leagris** [comment]
Potion mod has been removed

**Comment by DoomSquirter** [comment]
I thought I had already commented on this.  The rod became uncraftable after the potion mod was removed.

possibly this is a server issue.  if so can you make an alternative recipe?  I swear it's just a bottle of water where the potion is now.

**Comment by leagris** [comment]
Recipes perfectly work on server despite JEI seeing uncraftable potion.
