### ISSUE TITLE
Magma Island disabled so embossing impossible with Tinkers

### ISSUE THREAD

**Issue by Crumbology** [Beyond-Reality/Beyond-Realty-Farscapes#22]
As magma islands were disabled it's impossible to get the magma slime balls(the orange ones) which breaks tinkers embossing system which requires a magma slime crystal.

Would it be possible to get a recipe for that specific slime ball?

**Comment by leagris** [comment]
It is a feature.
Good time to start bee breeding for Magma Slimey Princess.
