### ISSUE TITLE
Quantum Suit is uncraftable

### ISSUE THREAD

**Issue by Cantankerous-Rex** [Beyond-Reality/Beyond-Realty-Farscapes#23]
When I put all the correct items in a crafting grid it will not let me craft any of the pieces.

**Comment by Cantankerous-Rex** [comment]
Lea I have left the items in some Tinks crafting grids on the upstairs of the temple. Its signposted for you. 

x 718, y 85, z 3323

**Comment by leagris** [comment]
Fixed on server and for next release
