### ISSUE TITLE
Fermenter will not accept crossbred saplings (Gendustry)

### ISSUE THREAD

**Issue by tworf** [Beyond-Reality/Beyond-Realty-Farscapes#27]
The Forestry Fermenter does not seem to accept cross-bred saplings (at least the ones created in the genetic imprinter).

Here is the Gendustry Cross-Bred sapling including NBT data
![cross-bred sapling](https://user-images.githubusercontent.com/2623873/27304451-088e309c-5536-11e7-8d0e-8b0f3b82bac6.png)

Here is the default Apple Oak Sapling from JEI also with NBT
![jei sapling](https://user-images.githubusercontent.com/2623873/27304459-0ebd0d94-5536-11e7-9646-73110b5a9801.png)

I can't really see anything wrong. 

I have tried breaking and replacing the fermenter, analysed and unanalysed saplings. I'm manually breeding a tree now to test.

**Comment by leagris** [comment]
The only difference is that your crossbred sapling has `sappinessHigh`
```JSON
{
  IsAnalyzed:0b,
  Genome:{
    Chromosomes:[
      0:{
        UID1:"forestry.treeOak",
        UID0:"forestry.treeOak",
        Slot:0b
      },
      1:{
        UID1:"forestry.hightLarge",
        UID0:"forestry.hightLarge",
        Slot:1b
      },
      2:{
        UID1:"forestry.saplingsHigh",
        UID0:"forestry.saplingsHigh",
        Slot:2b
      },
      3:{
        UID1:"forestry.fruitApple",
        UID0:"forestry.fruitApple",
        Slot:3b
      },
      4:{
        UID1:"forestry.yieldHigh",
        UID0:"forestry.yieldHigh",
        Slot:4b
      },
      5:{
        UID1:"forestry.sappinessHigh",
        UID0:"forestry.sappinessHigh",
        Slot:5b
      },
      6:{
        UID1:"forestry.leavesNone",
        UID0:"forestry.leavesNone",
        Slot:6b
      },
      7:{
        UID1:"forestry.maturationFaster",
        UID0:"forestry.maturationFaster",
        Slot:7b
      },
      8:{
        UID1:"forestry.i1d",
        UID0:"forestry.i1d",
        Slot:8b
      },
      9:{
        UID1:"forestry.fireproofFalse",
        UID0:"forestry.fireproofFalse",
        Slot:9b
      }
    ]
  }
}
```

**Comment by tworf** [comment]
Tried a vanilla sappinessHigh Sapling (Blue Mahoe) and this does seem to process correctly

**Comment by leagris** [comment]
Yes, the other difference is your non-working sapling was analyzed.

**Comment by tworf** [comment]
I did try both analysed and non-analysed as per the edited first post. weird

**Comment by leagris** [comment]
Fixed in next pack update.
