### ISSUE TITLE
crash while holding down control

### ISSUE THREAD

**Issue by DoomSquirter** [Beyond-Reality/Beyond-Realty-Farscapes#3]
https://pastebin.com/eC5EZ6Mq

just holding down control really, anywhere does this.

**Comment by tworf** [comment]
Have had the same issue, even when not holding ctrl (being tabbed out)

**Comment by leagris** [comment]
Just remove/disable placementpreview mod.
The Control Key is the triggers to enable Placement Preview and it is what is showing up into this crashlog

**Comment by DoomSquirter** [comment]
that worked great.  as always, thanks

**Comment by DoomSquirter** [comment]
Just FYI, problem still exists even with -r2.  just crashed, exact same situation on server.  

reopening.

**Comment by DoomSquirter** [comment]
mod removed, close issue if you feel it's appropriate to do so please.
