### ISSUE TITLE
Chisel and Bits unusable on server.

### ISSUE THREAD

**Issue by Crumbology** [Beyond-Reality/Beyond-Realty-Farscapes#31]
Cannot chisel blocks into bits or place bits at all on the server, works fine in my single player test world.

The blocks and bits interacted with disappear and place then reappear/disappear as if they are in protected spawn chunks.  All other blocks can be broken and placed as usual, left my claimed area, still couldn't use the mod.  Blocks already created with the mod are unaffected and can be broken and placed normally.

Doomsquirter also tried and couldn't use the mod so it's not a single client problem.

**Comment by leagris** [comment]
Downgraded to MCMultiPart-2.0.0 in next release 

Relates to:
https://github.com/AlgorithmX2/Chisels-and-Bits/issues/280
https://github.com/amadornes/MCMultiPart/issues/82

**Comment by Terpo** [comment]
Sry if I ask here, but does downgrading from MCMultipart 2.0.1 to 2.0.0 work and does it have any bad side effects? If everything works I will follow this path on my modpack too :).

**Comment by leagris** [comment]
it works
