### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by Kainmortal** [Beyond-Reality/Beyond-Realty-Farscapes#33]
When placing down cables from TechReborn mod and trying to break them with any pickaxe crashes the game.
Another crash happens when trying to open inventory in The End. This one didn't happen when i first entered, but when loading game again still being in The End, the inventory crash happens.

**Comment by leagris** [comment]
- TechReborn bugs will not be fixed, as TR Team decided to abandon 1.11.2 unfinished with all bugs.

- Crash with inventory in the end could not be reproduced.
