### ISSUE TITLE
ichisel interface stops working

### ISSUE THREAD

**Issue by DoomSquirter** [Beyond-Reality/Beyond-Realty-Farscapes#36]
so, will reference this issue, it seems fixed in a commit, not sure if commit rolled into a release:

https://github.com/Chisel-Team/Chisel/issues/464

**Comment by leagris** [comment]
Possibly here: https://minecraft.curseforge.com/projects/chisel/files/2441062

**Comment by leagris** [comment]
Fixed in next pack update
