### ISSUE TITLE
add certus (and possibly other ores) to IF laser

### ISSUE THREAD

**Issue by DoomSquirter** [Beyond-Reality/Beyond-Realty-Farscapes#37]
certus, ferrous/nickel,  platinum, possibly some of the other mod ores, would be nice to add those to the IF laser list in configs.

**Comment by DoomSquirter** [comment]
I see platinum but no certus or ferrous or any other ores on server.  Intended?

**Comment by DoomSquirter** [comment]
ok, rephrase, I see platinum assigned to a lens, but I guess I am seeing ferrous and other ores just showing up as part of the back scatter.  I guess this is what was intended.

**Comment by leagris** [comment]
This commit added:
```
            0 oreCertusQuartz 0 5
            0 oreCertusQuartzCharged 0 3
            1 oreArdite 0 3
            3 oreApatite 0 8
            3 oreMithril 0 4
            3 orePlatinum 0 2
            4 oreFluidGlowstone 0 6
            4 oreNickel 0 5
            7 oreSilicon 0 7
            7 oreThorium 0 2
            9 oreFluidEnder 0 3
            11 oreCobalt 0 3
            14 oreFluidRedstone 0 3
            15 oreFluidCrudeOilSand 0 5
            15 oreFluidCrudeOilShale 0 5
            15 oreTungsten 0 3
```

**Comment by leagris** [comment]
You don't see because your client config does not include these changes.
