### ISSUE TITLE
Pams Harvestcraft Market Spawn eggs

### ISSUE THREAD

**Issue by tworf** [Beyond-Reality/Beyond-Realty-Farscapes#5]
The market in Pams lets you buy seeds and other items like animal spawn eggs

Buying a cow spawn egg gives you a spawn egg item with no metadata.

**Comment by Ashkin** [comment]
I can verify.  I just bought two of them, and the eggs do not work.
The item says: Spawn 383:92 (Minecraft).


(FTB Presents Skyfactory 3 v 3.0.13 MC 1.10.2)
