### ISSUE TITLE
Modular Routers - mod filter causes client crash

### ISSUE THREAD

**Issue by ukdunc** [Beyond-Reality/Beyond-Realty-Farscapes#7]
I crafted the mod filter from moduler routers - you right click with it in hand to open the GUI but having tried it twice it cause.  Last crash report below.
[crash-2017-06-09_15.28.56-client.txt](https://github.com/Beyond-Reality/Beyond-Realty-Farscapes/files/1064322/crash-2017-06-09_15.28.56-client.txt)
s the client to crash each time.

**Comment by leagris** [comment]
Crash already reported here: https://github.com/desht/ModularRouters/issues/18
Waiting for upgrade with fix
