### ISSUE TITLE
Skull Dupe Glitch

### ISSUE THREAD

**Issue by cgalliva** [Beyond-Reality/Beyond-Realty-Farscapes#8]
Whenever you break a wither skull that's placed in the world, it drops 2. This happens everytime regardless of what you break it with.

I haven't tested it with other skull types at this point.

**Comment by tworf** [comment]
Confirmed with regular skeleton heads in roguelike dungeons and the dragons head from ships in the end. Place a single skull and get 2 when it drops.

**Comment by leagris** [comment]
Fixed in next release with update to [`Multi Mine 1.11.2-1.5.7` fixes Skull Blocks dropping twice](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/1.11.2/MultiMine/src/main/resources/changelog.txt#L5)
